version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 20G
        reservations:
          memory: 15G
    networks:
      - app-network

  frontend:
    image: node:16
    working_dir: /app/web-demo
    volumes:
      - ./web-demo:/app/web-demo
    command: >
      sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
